- name: configure frontend server
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: start and enable nginx service
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
    
  - name: delete  directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: create the directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: download application code
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip

  - name: unzip front code
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: copy conf file
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf

  - name: restart nginx service
    ansible.builtin.service:
      name: nginx
      state: restarted